conversate/urls.py
"""
Conversate URLs
"""
from django.urls import re_path

from . import views


app_name = "conversate"

urlpatterns = [
    re_path(
        r"^$",
        views.index,
        name="index",
    ),
    re_path(
        r"^(?P<room_slug>[-\w]+)/$",
        views.room,
        name="room",
    ),
    re_path(
        r"^(?P<room_slug>[-\w]+)/send/$",
        views.send,
        name="send",
    ),
    re_path(
        r"^(?P<room_slug>[-\w]+)/file/(?P<message_id>\d+)/$",
        views.download_file,
        name="file",
    ),
    re_path(
        r"^(?P<room_slug>[-\w]+)/settings/$",
        views.update_settings,
        name="settings",
    ),
    #
    # JSON API
    #
    re_path(
        r"^(?P<room_slug>[-\w]+)/api/$",
        views.api_base,
        name="api_base",
    ),
    re_path(
        r"^(?P<room_slug>[-\w]+)/api/poll/$",
        views.api_check,
        name="api_check",
    ),
    re_path(
        r"^(?P<room_slug>[-\w]+)/api/send/$",
        views.api_send,
        name="api_send",
    ),
    re_path(
        r"^(?P<room_slug>[-\w]+)/api/history/$",
        views.api_history,
        name="api_history",
    ),
]

conversate/templates/conversate/includes/room_input.html
<table>
    <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>
            <form
                method="POST"
                action="{% url "conversate:send" room_slug=room.slug %}"
                autocomplete="off"
                enctype="multipart/form-data"
            >
                {% csrf_token %}
                {{ form.content }}

                <div class="cnv_input__file">
                    <input type="checkbox" id="cnv_input__toggler-file">
                    <label for="cnv_input__toggler-file">Upload file</label>
                    <div>
                        {{ form.file }}
                    </div>
                </div>
                <input type="submit" value="Send">
            </form>
        </td>
    </tr>
</table>

conversate/templates/conversate/includes/room_messages.html
{% load conversate %}

<div class="cnv_messages_inner">
    <div class="cnv_table_con">
        <table class="cnv_table">
            <tr>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>{% if remaining == 0 %}No older messages{% else %}Older messages hidden{% endif %}</td>
            </tr>

            {% for message in room_messages %}
            <tr class="cnv_user_{{ message.user.username }}">
                <td data-time="{{ message.timestamp }}">{{ message.timestamp|naturaltimestamp }}</td>
                <td>{{ message.user.username }}</td>
                <td>{{ message.render|safe }}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>

conversate/templates/conversate/includes/room_sidebar.html
{% load conversate %}

<h1>Users</h1>
<table class="cnv_users">
    {% for user in room_users %}
    <tr class="cnv_{% if user.active %}{% if user.has_focus%}active{% else %}afk{% endif %}{% else %}inactive{% endif %} cnv_user_{{ user.username }}"><th>{{ user.username }}</th><td title="Last ping: {{ user.last_seen|naturaltimedelta }}">{{ user.last_spoke|naturaltimedelta }}</td></tr>
    {% endfor %}
</table>

<h1>Settings</h1>
<form method="POST" action="{% url "conversate:settings" room_slug=room.slug %}" class="cnv_form" autocomplete="off">
    {% csrf_token %}
    <div class="cnv_settings">
        {{ settings.as_p }}
    </div>
    <div class="cnv_submit">
        <input type="submit" value="Save">
    </div>
</form>

<style>
{% for user in room_users %}
    .cnv_users tr.cnv_user_{{ user.username }} th,
    .cnv_content tr.cnv_user_{{ user.username }} td:nth-child(n+2) {
        color: #{{ user.colour }};
    }

    @media all and (max-width:640px) {
        .cnv_content tr.cnv_user_{{ user.username }} td:nth-child(3) {
            color: #000;
        }
        .cnv_content tr:not(.cnv_user_{{ user.username }}) + tr.cnv_user_{{ user.username }} td {
            border-bottom: 0;
        }
        .cnv_content tr.cnv_user_{{ user.username }} + tr.cnv_user_{{ user.username }} td {
            border: 0;
        }
        .cnv_content tr.cnv_user_{{ user.username }} + tr.cnv_user_{{ user.username }} td:nth-child(-n+2) {
            display: none;
        }
    }
{% endfor %}
</style>